### ISSUE TITLE
yaml直接导入会崩溃，文件导入也会报错

### ISSUE THREAD

**Issue by SnowWolf817** [laijinxian/flutter_3des_plugin#3]
MissingPluginException(No implementation found for method encrypt on channel flutter_3des_plugin)

**Comment by laijinxian** [comment]
不好意思，忘看issues了。 你意思直接在yaml里引入插件就报错么；还是在dart文件引入报错； 你的flutter版本是多少

**Comment by laijinxian** [comment]
您的flutter是多少，报错信息贴一下
